export const CONFIG = {
  colors: {
    sky: 0x87ceeb,
    snow: 0xffffff,
    tree: 0x2d3436,
    rock: 0x808080,
    jacket: 0xd4a017,
    pants: 0x1a1a1a,
    helmet: 0xffffff,
    goggles: 0x111111,
    backpack: 0x333333,
    box: 0xf1c40f,
    elevatedBox: 0xffd700,
    boost: 0x2ecc71,
    shield: 0x00ffff,
    ramp: 0x95a5a6,
  },
  physics: {
    maxSpeed: 0.85,
    boostSpeed: 1.05,
    acceleration: 0.0045,
    friction: 0.98,
    carveFriction: 0.997,
    carveMaxSpeedFrac: 0.75,
    carveAccelScale: 0.25,
    carveTurnInterpolation: 0.25,
    steerNoUpFriction: 0.998,
    steerNoUpMinSpeed: 0.35,
    steerOnlyMaxSpeedFrac: 0.75,
    steerDownFriction: 0.97,
    steerDownMinSpeed: 0.01,
    steerDownLeanBack: 0.55,
    steerDownExtraTurnRad: Math.PI / 4,
    steerDownOnlyAccel: 0.002,
    steerNoUpTurnScale: 0.5,
    accelNoUpScale: 0.55,
    accelUpOnlyScale: 0.88,
    accelDownOnlyScale: 1.0,
    straightLineFriction: 0.997,
    gravity: 0.02,
    jumpForceShort: 0.22,
    jumpChargeDurationMs: 600,
    jumpForceMax: 0.5,
    rampForce: 0.4,
    rampAssistWindow: 50 / 60,
    rampAssistBoost: 0.32,
    spinOutThreshold: 1.5,
    spinOutDuration: 1,
  },
  game: {
    maxHP: 100,
    maxLives: 3,
    invincibleTime: 10,
    dynamiteTime: 5,
    dynamiteDamage: 85,
    boostDuration: 3,
    baseSpawnRate: 0.2,
  },
  world: {
    playAreaWidth: 72,
    obstacleZoneMargin: 8,
  },
  // Set to { logCharacterLoad: true } to log character load/apply diagnostics.
  debug: { logCharacterLoad: true },
  // Asset URLs (served from public/). Omit or set to "" to use procedural fallback.
  assets: {
    basePath: "/assets",
    /** Scale applied to the glTF character. Use 1 for meter-based models (e.g. Onirix), 0.01 for cm-based. */
    characterScale: 55,
    /** Pipeline test: when set, used instead of character for loading (lets you keep character: "" for procedural). Duck from Khronos glTF Sample Models. */
    characterTest: "/assets/character/snowboarder.glb",
    character: "/assets/character/snowboarder.glb",
    sky: "/assets/sky/env.hdr",
    terrain: {
      heightmap: "",
      snowAlbedo: "",
      snowNormal: "",
      snowRoughness: "",
    },
    obstacles: {
      tree: "/assets/obstacles/tree.glb",
      rock: "/assets/obstacles/rock.glb",
      box: "/assets/obstacles/box.glb",
      ramp: "/assets/obstacles/ramp.glb",
    },
  },
};
